version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shogi-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l8vrn3nvj2o7"
s3_prefix = "shogi-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
